### ISSUE TITLE
Ability to "lock" everything so that only the owner can access or those they list

### ISSUE THREAD

**Issue by AmyMoriyama** [theFox6/microexpansion#11]
**Is your feature request related to a problem? Please describe.**
Players can steal items. It's logical that there should be an ability to "lock" the terminal and other bits and pieces. It is also logical that the owner could list playernames that are allowed access when locked.

**Describe the solution you'd like**
Ability to lock everything.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by SwissalpS** [comment]
use ``minetest.is_protected()`` so protection mods can be used to controll access

**Comment by theFox6** [comment]
The drive now respects `minetest.is_protected` however the inventory of the network is detached, so protection is not that easy.
I would like protection to be settable with a separate protection controller that the network owner can use to setup which player may do what.

**Comment by JamesClarke7283** [comment]
Please pin this issue, someone robbed us in our world, abusing this flaw.

**Comment by theFox6** [comment]
In the [latest release](https://github.com/theFox6/microexpansion/releases/tag/v1.1.1) I have added the Security Terminal.
It allows setting up permissions for ME Networks.

By default only the owner of the network controller will receive "full" access.
The security terminal can be used to allow other players to interact with the ME Network as well.

I hope this stops the thievery. ^^

**Comment by SwissalpS** [comment]
I gave part of the new code a quick glance. Two things popped out.
- the networks are stored in a serialized flat file. Have you looked into using modstorage instead?
- it seems that file is only saved on server shutdown. A crash could cause a lot of lost items.

(I may be wrong, I only spent a few minutes looking over one file)

**Comment by theFox6** [comment]
> I gave part of the new code a quick glance. Two things popped out.
> 
>     * the networks are stored in a serialized flat file. Have you looked into using modstorage instead?
> 
>     * it seems that file is only saved on server shutdown. A crash could cause a lot of lost items.
> 
> 
> (I may be wrong, I only spent a few minutes looking over one file)

These concerns are valid and I am working on migrating and improving this.
