### ISSUE TITLE
crash when retrieving item from terminal

### ISSUE THREAD

**Issue by SwissalpS** [theFox6/microexpansion#14]
**Describe the bug**
game crash

**To Reproduce**
1. after clicking on 'to drive' in terminal, my inv moved to the terminal
2. so I shift-clicked on an item to get it back into my inv
3. game crashed

**Expected behavior**
that my item goes to inv and that game doesn't crash

**Log**
```
AsyncErr: Lua: Runtime error from mod '??' in callback detached_inventory_OnTake(): InventoryList 'main' is currently in use and cannot be deleted or resized.
stack traceback:
	[C]: in function 'set_size'
	...t/bin/../mods/microexpansion/modules/network/network.lua:158: in function 'remove_slots'
	...t/bin/../mods/microexpansion/modules/network/network.lua:191: in function 'set_storage_space'
	...t/bin/../mods/microexpansion/modules/network/network.lua:242: in function <...t/bin/../mods/microexpansion/modules/network/network.lua:241>
```

**Desktop (please complete the following information):**
 - Minetest version: 5.8.0-dev
 - Other mods activated: minimal setup

**Comment by BRNSystems** [comment]
I have the same issue. It seemed to arise after I was using it for a while

**Comment by theFox6** [comment]
This should now be fixed in the latest release. For some reason minetest doesn't allow modifying inventory size right after items have been taken.
