### ISSUE TITLE
CRASHES on old worlds: attempt to index local 'meta' (a nil value) in network:fallback_access()

### ISSUE THREAD

**Issue by JamesClarke7283** [theFox6/microexpansion#15]
**Describe the bug**
Any old worlds that don't have the new security terminal, will crash.

**To Reproduce**
If known, steps to reproduce the behavior:
1. Start the game on a older world

**Expected behavior**
Game starts up, and i can use the ME Terminal, etc.

**Log**
[Link to log](https://pastebin.com/m7zCyhTb)
I added some extra logging to the file to capture the behavior.

**Desktop (please complete the following information):**
 - Minetest version: 5.7.0 (Linux)

 - Other mods activated: basic_materials, i3, inventory_pouches, item_tracking, mesecons, modular_computers

**Additional context**
I tried using get_node as well, it still returns nil, its quite an odd bug.
The position of the controller node appears to be correct, and even hardcoding the position when getting the metadata, still returns nil. i Suggest its an issue with the loading order of the mod.

**Comment by theFox6** [comment]
I should have gone to sleep yesterday instead of trying to push this release...
I hope the new LBM to update networks fixes that issue.
