### ISSUE TITLE
Huge duplication bug

### ISSUE THREAD

**Issue by AFCMS** [theFox6/microexpansion#3]
**Describe the bug**
Adding in me drive many objects with metadata copy first object's metadata to all other.
It isn't possible to add in me drive by drag-n-drop many object with metadata, but add them with sneak+click work.
It is a huge bug because in 1mn, with small material, I can multiply by 7 a number (limited to 64000) of diamonds blocks...
Or overpower ingot...

**To Reproduce**
You only need : 

- 1x me drive
- 2x me cable
- 1x me terminal
- 8x 1k me cell
- 10x diamond block

My video : https://drive.google.com/file/d/1nYRdCKdRZSG2EKTNTq_nKJRY4NPpPH00/view?usp=sharing
Video is made with Minetest 5.0, but the bug work with Minetest 5.2

**Expected behavior**
Do not stack objects with metadata.
They should be added, but not stacked.

**Desktop (please complete the following information):**
 - Minetest version: 5.2

**Comment by theFox6** [comment]
Oh yeah looks like I didn't pay attention to the metadata of the added items.

**Comment by AFCMS** [comment]
Tools could be stacked if they have not be used.

**Comment by theFox6** [comment]
I haven't tested yet, but it might be fixed in https://github.com/theFox6/microexpansion/commit/347cec589400f7d1758492c7c7ccc2d8fd7225a0

**Comment by AFCMS** [comment]
Duplication bug is resolved, but there is a linked bug again:
https://drive.google.com/file/d/14i8VjOUgIkRAksovwHLb6dMPTSBEiJ89/view?usp=sharing
https://drive.google.com/file/d/1FgAKdkgpGmq1i1Bp6RirDPYDiXcdSG0Z/view?usp=sharing

**Comment by theFox6** [comment]
I can't view those images, google wants me to log in for that...
Have you tried attaching them to your issue comment or does GitHub complain?

**Comment by AFCMS** [comment]
Oh, sory.
New link:
https://drive.google.com/file/d/14i8VjOUgIkRAksovwHLb6dMPTSBEiJ89/view?usp=sharing
https://drive.google.com/file/d/1FgAKdkgpGmq1i1Bp6RirDPYDiXcdSG0Z/view?usp=sharing
There are too big for Github.

**Comment by AFCMS** [comment]
It's work perfectly with last commit for cells, but not with tools: tools copy their durability (like cells in #3) and stack.

**Comment by AFCMS** [comment]
Any information about the bug ?

**Comment by theFox6** [comment]
I know that there is still a problem with tools, I haven't investigated that yet. I have been a little busy in the last few months but I hope to get this fixed soon.

**Comment by Gerold55** [comment]
> **Describe the bug**
> Adding in me drive many objects with metadata copy first object's metadata to all other.
> It isn't possible to add in me drive by drag-n-drop many object with metadata, but add them with sneak+click work.
> It is a huge bug because in 1mn, with small material, I can multiply by 7 a number (limited to 64000) of diamonds blocks...
> Or overpower ingot...
> 
> **To Reproduce**
> You only need :
> 
> * 1x me drive
> * 2x me cable
> * 1x me terminal
> * 8x 1k me cell
> * 10x diamond block
> 
> My video : https://drive.google.com/file/d/1nYRdCKdRZSG2EKTNTq_nKJRY4NPpPH00/view?usp=sharing
> Video is made with Minetest 5.0, but the bug work with Minetest 5.2
> 
> **Expected behavior**
> Do not stack objects with metadata.
> They should be added, but not stacked.
> 
> **Desktop (please complete the following information):**
> 
> * Minetest version: 5.2

You forgot about the autocrafters and the portable terminal

**Comment by theFox6** [comment]
> You forgot about the autocrafters and the portable terminal

Is this related to the duplication issue?

**Comment by theFox6** [comment]
I think I have fixed all duplication issues now.
Please tell me if you find any that I have forgotten or close the issue if there are no more duplication bugs.

**Comment by AFCMS** [comment]
It's work perfectly !!! Thank you !
