### ISSUE TITLE
Getting stack from terminal bug

### ISSUE THREAD

**Issue by AFCMS** [theFox6/microexpansion#8]
**Describe the bug**
You have a stack with more than `stack_max` in a terminal ;
You shift-click on it ;
You get `stack_max` of the item and the entire stack disappears from the terminal.

**Expected behavior**
You get only `stack_max` of the item and `stack_max` is subtracted to the terminal.
Or listring must be disabled.

**Desktop (please complete the following information):**
 - Minetest version: 5.3

**Comment by theFox6** [comment]
This was a fault from minetest's side taking more than possible. The latest version of minetest only takes as much as possible from a listring.
Also it didn't treat the on_take function correctly.
I can still try to fix this bug with old minetest versions if you want me to.

**Comment by AFCMS** [comment]
> This was a fault from minetest's side taking more than possible. The latest version of minetest only takes as much as possible from a listring.
> Also it didn't treat the on_take function correctly.
> I can still try to fix this bug with old minetest versions if you want me to.

What about just removing listring from the form?

**Comment by theFox6** [comment]
I do like putting stacks into the terminal via shift+click...
However if you are concerned that this is a problem (for example because you use an older minetest version), I can still fix the problem if you want me to.

**Comment by AFCMS** [comment]
I use 5.4

**Comment by theFox6** [comment]
I could not reproduce the issue anymore on newer minetest versions, so I will close this issue.
Feel free to reopen if it somehow pops up again.
